language: minimal
sudo: required
dist: xenial
cache:
  directories:
    - /home/travis/.cache/bazel/
services:
  - docker
matrix:
  include:
   - os: linux
     arch: amd64
     env: RUNSC_PATH=./bazel-bin/runsc/linux_amd64_pure_stripped/runsc
   - os: linux
     arch: arm64
     env: RUNSC_PATH=./bazel-bin/runsc/linux_arm64_pure_stripped/runsc
script:
   - bash -xe ./scripts/travis.sh
branches:
  except:
  # Skip copybara branches.
  - /^test\/cl.*$/
