language: minimal
sudo: required
dist: xenial
services:
  - docker
env:
  - TEST_SUITE=make
  - TEST_SUITE=docker
  - TEST_SUITE=syscalls-aq
  - TEST_SUITE=syscalls-rz
  - TEST_SUITE=unit
script:
  - ./travis/test.sh
