language: minimal
sudo: required
dist: xenial
cache:
  directories:
    - /home/travis/.cache/bazel/
services:
  - docker
matrix:
  include:
   - os: linux
     arch: amd64
     env: RUNSC_PATH=./bazel-bin/runsc/linux_amd64_pure_stripped/runsc
   - os: linux
     arch: arm64
     env: RUNSC_PATH=./bazel-bin/runsc/linux_arm64_pure_stripped/runsc
script:
   - uname -a
   - make DOCKER_RUN_OPTIONS="" BAZEL_OPTIONS="build runsc:runsc" bazel && for i in `seq 10`; do $RUNSC_PATH --alsologtostderr --network none --strace --debug --TESTONLY-unsafe-nonroot=true --rootless do ls || exit 1; done
