cache:
  directories:
    - /home/travis/.cache/bazel/
language: minimal
sudo: required
dist: xenial
services:
  - docker
env:
  - TEST_SUITE=make
  - TEST_SUITE=docker
  - TEST_SUITE=syscalls
  - TEST_SUITE=unit
script:
  - ./travis/test.sh
